# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
## Node version: v12.22.12

# Site
# title: PengLe's Blog
title: 个人感悟记录
subtitle: 爱读书，爱旅行，爱创作。
description: PengLe's Blog | 一个记录个人成长的地方
keywords: 张鹏乐,鹏乐,PengLe Zhang,PengLe,白泽,京东集团,京东零售-企业业务,军事科学院,系统所,总装,国防科学技术大学,国防科大-信息系统与管理学院,石家庄外国语学校,石家庄43中,北京,石家庄,大数据,数据科学家,数据工程师,数据架构师,数据分析师,数据采集,数据仓库,数据建模,数据BI,AI,Big Data,Data Scientist,Data Engineer,Data Architect,Data Analyst,Data Ingestion,Data WaraHouse,Data Model,Modern Data Stack.
author: PengLe Zhang
language:
  - zh-CN
  - en
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.paulplayer.com/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - .github/**/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - CNAME
  - robots.txt
  - .github/**/**
exclude:
  - urls.txt
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/

## Themes: https://hexo.io/themes/
theme: hueman

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  message: hxBlog
  name: paulplayer
  email: paulplayergg@gmail.com
  repo: 
    github: git@github.com:paulplayer/paulplayer.github.io.git,master
  ignore_hidden:
    public: false


# hexo-filter-cleanup
hfc_useref:
  enable: true
  concat: true
  exclude: 
hfc_html:
  enable: true
  exclude: 
hfc_css:
  enable: true
  exclude: 
    - '*.min.css'
hfc_js:
  enable: true
  mangle: true
  compress:
  exclude: 
    - '*.min.js'
hfc_img:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: false
  jpegrecompressQuality: 'medium'
  optipng: true
  svgo: true
hfc_favicons:
  enable: true
  src: css/images/logo-header.png
  target: css/images/
  html: true
  opts: false
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false

# lazyload
lazyload:
  enable: true
  onlypost: true # optional
  loadingImg: /css/images/loading.gif # optional eg ./images/loading.gif
  isSPA: false # optional
  preloadRatio: 3 # optional, default is 1

## Google Sitemap
sitemap:
  path: sitemap.xml 

## Baidu Sitemap
baidusitemap:
  path: baidusitemap.xml

## RSS feed
feed:
    type: atom
    path: atom.xml
    limit: 20